btc_nasdaq:
  outputs:
    dev:
      dbname: datalake
      host: datalake-warehouse
      pass: datalake_pass
      port: 5432
      schema: btc_nasdaq
      threads: 1
      type: postgres
      user: datalake_user
  target: dev
